{
  "headers": {
    "host": "localhost:8081",
    "connection": "keep-alive",
    "content-length": "317",
    "sec-ch-ua": "\"Not A(Brand\";v=\"99\", \"Microsoft Edge\";v=\"121\", \"Chromium\";v=\"121\"",
    "client_id": "11612fa19a174c0db4a88b543671f790",
    "x-correlation-id": "post",
    "sec-ch-ua-mobile": "?0",
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0",
    "content-type": "application/json",
    "client_secret": "EE7d3B46c93e40308936C89A38307529",
    "sec-ch-ua-platform": "\"Windows\"",
    "accept": "*/*",
    "origin": "http://localhost:8081",
    "sec-fetch-site": "same-origin",
    "sec-fetch-mode": "cors",
    "sec-fetch-dest": "empty",
    "referer": "http://localhost:8081/console/",
    "accept-encoding": "gzip, deflate, br",
    "accept-language": "en-US,en;q=0.9"
  },
  "clientCertificate": null,
  "method": "POST",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/api/customer",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/customer",
  "listenerPath": "/api/*",
  "localAddress": "/127.0.0.1:8081",
  "relativePath": "/api/customer",
  "uriParams": {},
  "rawRequestUri": "/api/customer",
  "rawRequestPath": "/api/customer",
  "remoteAddress": "/127.0.0.1:60355",
  "requestPath": "/api/customer"
}